<?php

declare(strict_types=1);

namespace Maatify\Slug\Enum;

enum HistoryEventTypeEnum: string
{
    case ASSIGNED = 'ASSIGNED';
    case CHANGED = 'CHANGED';
    case RESTORED = 'RESTORED';
    case ALIAS_ADDED = 'ALIAS_ADDED';
    case ALIAS_RETIRED = 'ALIAS_RETIRED';
    case ALIAS_REACTIVATED = 'ALIAS_REACTIVATED';
    case ALIAS_PROMOTED = 'ALIAS_PROMOTED';
    case DEACTIVATED = 'DEACTIVATED';
    case REACTIVATED = 'REACTIVATED';
    case SCOPE_TRANSITIONED_OUT = 'SCOPE_TRANSITIONED_OUT';
    case SCOPE_TRANSITIONED_IN = 'SCOPE_TRANSITIONED_IN';
    case OWNERSHIP_RELEASED = 'OWNERSHIP_RELEASED';
    case OWNERSHIP_RELEASED_ALL = 'OWNERSHIP_RELEASED_ALL';
    case OWNERSHIP_TRANSFERRED_OUT = 'OWNERSHIP_TRANSFERRED_OUT';
    case OWNERSHIP_TRANSFERRED_IN = 'OWNERSHIP_TRANSFERRED_IN';
    case ADOPTED_CURRENT = 'ADOPTED_CURRENT';
    case ADOPTED_HISTORICAL = 'ADOPTED_HISTORICAL';
    case ADOPTED_ALIAS = 'ADOPTED_ALIAS';
}
